import '../audio/motion/heartbeat_motion_state_controller.dart';
import '../audio/motion/heartbeat_orchestrator.dart';
import '../audio/processing/audio_signal_processor.dart';
import '../models/device_models.dart';
import '../models/enums.dart';

class HeartbeatOrchestratorInputMapper {
  const HeartbeatOrchestratorInputMapper();

  HeartbeatOrchestratorInput map({
    required AudioFeatures features,
    required StimMode mode,
    required OutputModeSelection outputMode,
    required double sensitivity,
    required double intensityCap,
    required double dtSec,
    required int nowMs,
    required bool hasRecentPcm,
    required double onsetSensitivityMin,
    required double onsetSensitivityMax,
    required double onsetSmoothing,
    required HeartbeatMotionStateController motionState,
    required double fillBaseRadius,
    required double fillHhImpulseSize,
    required double fillHhDecayRate,
    required double fillRotOmega,
    required bool buttonHoldMuted,
    required double buttonHoldRamp,
    required double buttonResumeRampSec,
    required CalibrationPattern calibrationPattern,
    required bool manualPulseMode,
    required double manualPulseHz,
    required double pulseMinHz,
    required double pulseMaxHz,
    required double bassMonitorLowHz,
    required double bassMonitorHighHz,
    required bool tempoUnlockHoldEnabled,
    required double energyResponseStrength,
    required double latencyCompensationMs,
    required double adaptiveLeadMs,
    required bool learningEnabled,
    required int committedCadenceHint,
    required bool hardFillGateEnabled,
  }) {
    return HeartbeatOrchestratorInput(
      features: features,
      mode: mode,
      outputMode: outputMode,
      sensitivity: sensitivity,
      intensityCap: intensityCap,
      dtSec: dtSec,
      nowMs: nowMs,
      hasRecentPcm: hasRecentPcm,
      onsetSensitivityMin: onsetSensitivityMin,
      onsetSensitivityMax: onsetSensitivityMax,
      onsetSmoothing: onsetSmoothing,
      fluxEmaPhrase: motionState.fluxEmaPhrase,
      phraseCommitted: motionState.phraseCommitted,
      phraseBeatCount: motionState.phraseBeatCount,
      phraseFluxAtStart: motionState.phraseFluxAtStart,
      lastBeatTriggerMs: motionState.lastBeatTriggerMs,
      fillSilenceStartMs: motionState.fillSilenceStartMs,
      fillTransition: motionState.fillTransition,
      fillAngle: motionState.fillAngle,
      fillHhImpulse: motionState.fillHhImpulse,
      fillBaseRadius: fillBaseRadius,
      fillHhImpulseSize: fillHhImpulseSize,
      fillHhDecayRate: fillHhDecayRate,
      fillRotOmega: fillRotOmega,
      buttonHoldMuted: buttonHoldMuted,
      buttonHoldRamp: buttonHoldRamp,
      buttonResumeRampSec: buttonResumeRampSec,
      calibrationPattern: calibrationPattern,
      smoothedDominantBassHz: motionState.smoothedDominantBassHz,
      manualPulseMode: manualPulseMode,
      manualPulseHz: manualPulseHz,
      pulseMinHz: pulseMinHz,
      pulseMaxHz: pulseMaxHz,
      bassMonitorLowHz: bassMonitorLowHz,
      bassMonitorHighHz: bassMonitorHighHz,
      tempoUnlockHoldEnabled: tempoUnlockHoldEnabled,
      energyResponseStrength: energyResponseStrength,
      latencyCompensationMs: latencyCompensationMs,
      adaptiveLeadMs: adaptiveLeadMs,
      learningEnabled: learningEnabled,
      committedCadenceHint: committedCadenceHint,
      hardFillGateEnabled: hardFillGateEnabled,
    );
  }
}
